---
- name: include a play for server setup
  ansible.builtin.import_playbook: playbooks/main.yml
  tags: never

- name: configure server
  hosts: server
  become: true
  gather_facts: false
  tasks:
    - name: upload nixos configuration files
      ansible.posix.synchronize:
        mode: push
        src: configs/
        dest: /etc/nixos/
        rsync_opts: "--chown=root:root"
      notify: apply config

  handlers:
    - name: check compilation
      ansible.builtin.command: nixos-rebuild build
      register: build_output
      ignore_errors: true
      listen: apply config

    - name: success
      ansible.builtin.debug:
        msg: "{{ build_output.stderr_lines }}"
      when: build_output.rc == 0
      listen: apply config

    - name: error
      ansible.builtin.debug:
        msg: "{{ build_output.stderr_lines }}"
      when: build_output.rc == 1
      listen: apply config

    - name: stop
      ansible.builtin.meta: end_host
      when: build_output.rc == 1
      listen: apply config

    - name: rebuild system
      ansible.builtin.raw: nixos-rebuild switch
      register: switch_output
      ignore_errors: true
      listen: apply config

    - name: success
      ansible.builtin.debug:
        msg: "{{ switch_output.stdout_lines }}"
      when: switch_output.rc == 0
      listen: apply config

    - name: error
      ansible.builtin.debug:
        msg: "{{ switch_output.stdout_lines }}"
      when: switch_output.rc == 1
      listen: apply config

    - name: stop
      ansible.builtin.meta: end_host
      when: switch_output.rc == 1
      listen: apply config

  post_tasks:
    - name: gather facts about remote host
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'

    - name: get stats of ca and client certificate files
      ansible.builtin.stat:
        path: /mnt/ssd/services/ca/{{ item }}
      loop:
        - ca.pem
        - user.pfx
      register: certificates

    - name: copy ca and client certificate from server to local machine
      ansible.posix.synchronize:
        mode: pull
        src: /mnt/ssd/services/ca/{{ item }}
        dest: ./
      loop:
        - ca.pem
        - user.pfx
      when:
        - certificates.results.0.stat.exists
        - certificates.results.1.stat.exists
