---
- name: include a play for server setup
  ansible.builtin.import_playbook: playbooks/main.yml
  tags: never

- name: configure server
  hosts: server
  become: true
  gather_facts: false
  tasks:
    - name: upload nixos configuration files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /etc/nixos/
      with_fileglob: configs/*
      notify: apply config

  handlers:
    - name: check compilation
      ansible.builtin.command: nixos-rebuild build
      listen: apply config

    - name: rebuild system
      ansible.builtin.command: nixos-rebuild switch
      register: rebuild_output
      listen: apply config

    - name: display rebuild output
      ansible.builtin.debug:
        msg: "{{ rebuild_output.stderr_lines }}"
      listen: apply config

  post_tasks:
    - name: gather facts about remote host
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'

    - name: copy ca and client certificates from server to local machine
      ansible.posix.synchronize:
        mode: pull
        src: /mnt/ssd/services/ca/{{ item }}
        dest: ./
      loop:
        - ca.pem
        - user.pfx
