{
 "title": "GitLab Omnibus - Gitaly",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "gitlab-gitaly,praefect-gitaly" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{% raw %}{{instance}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Gitaly Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "topk(1, count by (version) (gitlab_build_info{job=~\"$job\",instance=~\"$instance\"}))",
     "legendFormat": "{% raw %}{{version}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_goroutines{instance=~\"$instance\"})",
     "legendFormat": "Go routines"
    },
    {
     "expr": "avg(process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "Open FDs (file descriptors)"
    }
   ]
  },
  {
   "title": "Git Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "topk(1, count by (git_version) (gitlab_build_info{job=~\"$job\",instance=~\"$instance\"}))",
     "legendFormat": "{% raw %}{{version}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{instance=~\"$instance\"})",
     "legendFormat": "Next GC"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without (grpc_method,grpc_service,grpc_type) (\n  rate(grpc_server_started_total{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{% raw %}{{instance}}{% endraw %}"
    }
   ]
  }
 ]
}