{
 "title": "GitLab Omnibus - Registry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"gitlab-registry\"}, instance)"
    }
   },
   {
    "name": "handler",
    "query": {
     "query": "label_values(registry_http_requests_total{instance=\"$instance\"}, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (\n  rate(registry_http_requests_total{instance=\"$instance\",handler=~\"$handler\"}[$__interval])\n)",
     "legendFormat": "{% raw %}{{handler}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(registry_http_request_duration_seconds_bucket{instance=\"$instance\",handler=~\"$handler\"}[$__interval])\n) > 0",
     "legendFormat": "{% raw %}{{le}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (\n  rate(registry_http_requests_total{instance=\"$instance\"}[$__interval])\n)",
     "legendFormat": "{% raw %}{{code}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{instance=\"$instance\",type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{instance=\"$instance\",type=\"Request\"}[$__interval]))",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Cache Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{instance=\"$instance\",type=\"Request\"}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}