{
 "title": "cAdvisor Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"integrations/node_exporter\"}, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{job=\"integrations/cadvisor\", instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Integration Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\",job=\"integrations/cadvisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Metric Received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_last_seen{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cpu=\"total\",instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}[$__interval])",
     "legendFormat": "{% raw %}{{cpu}}{% endraw %}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cpu=\"total\",instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "(\n  container_spec_memory_limit_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n-\n  container_memory_working_set_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n)\n",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"})\n/\navg(container_spec_memory_limit_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"})\n* 100\n"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (device) (\n  container_fs_usage_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n  /\n  container_fs_limit_bytes{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (\n  max by (device) (\n    container_fs_inodes_free{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n    /\n    container_fs_inodes_total{instance=\"$instance\",job=\"integrations/cadvisor\",name=\"$container\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=\"$instance\",interface=\"eth0\",job=\"integrations/cadvisor\",name=\"$container\"}[$__interval])",
     "legendFormat": "Network Received"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{instance=\"$instance\",interface=\"eth0\",job=\"integrations/cadvisor\",name=\"$container\"}[$__interval])",
     "legendFormat": "Network Transmitted"
    }
   ]
  }
 ]
}