{
 "title": "Node Exporter Dashboard",
 "description": "A quickstart to setup Prometheus Node Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"integrations/node_exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"integrations/node_exporter\", mode=\"idle\", instance=\"$instance\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"integrations/node_exporter\", mode=\"idle\", instance=\"$instance\"})\n)\n",
     "legendFormat": "{% raw %}{{cpu}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"integrations/node_exporter\", instance=\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"integrations/node_exporter\", instance=\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"integrations/node_exporter\", instance=\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"integrations/node_exporter\", instance=\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"})\n/\n  avg(node_memory_MemTotal_bytes{job=\"integrations/node_exporter\", instance=\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"integrations/node_exporter\", instance=\"$instance\", device!=\"\"}[$__interval])",
     "legendFormat": "{% raw %}{{device}}{% endraw %} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"integrations/node_exporter\", instance=\"$instance\", device!=\"\"}[$__interval])",
     "legendFormat": "{% raw %}{{device}}{% endraw %} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"integrations/node_exporter\", instance=\"$instance\", device!=\"\"}[$__interval])",
     "legendFormat": "{% raw %}{{device}}{% endraw %} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage /",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint=\"/\"}\n  -\n    node_filesystem_avail_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint=\"/\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job='integrations/node_exporter',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var|boot|nix).*',mountpoint!=''} / node_filesystem_size_bytes{job='integrations/node_exporter',instance='$instance'}",
     "legendFormat": "{% raw %}{{mountpoint}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk Space Usage /mnt/ssd",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint=\"/mnt/ssd\"}\n  -\n    node_filesystem_avail_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint=\"/mnt/ssd\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Disk Space Usage /mnt/hdd",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint=\"/mnt/hdd\"}\n  -\n    node_filesystem_avail_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"integrations/node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint=\"/mnt/hdd\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Disk Fill Up Time",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job='integrations/node_exporter',instance='$instance'} - node_filesystem_free_bytes{job='integrations/node_exporter',instance='$instance'}) / deriv(node_filesystem_free_bytes{job='integrations/node_exporter',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var|boot|nix).*',mountpoint!=''}[3d]) > 0",
     "legendFormat": "{% raw %}{{mountpoint}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"integrations/node_exporter\", instance=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{% raw %}{{device}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"integrations/node_exporter\", instance=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{% raw %}{{device}}{% endraw %}"
    }
   ]
  }
 ]
}