{
 "title": "Windows Exporter Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(windows_exporter_build_info{job=\"integrations/windows_exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 -\n    irate(windows_cpu_time_total{instance=\"$instance\",job=\"integrations/windows_exporter\",mode=\"idle\"}[$__rate_interval]))\n    /\n    ignoring(core) group_left\n    count without (core)( windows_cpu_time_total{instance=\"$instance\",job=\"integrations/windows_exporter\",mode=\"idle\"}\n  )\n)",
     "legendFormat": "{% raw %}{{core}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  windows_cs_physical_memory_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}\n  -\n  windows_os_physical_memory_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}\n)",
     "legendFormat": "memory used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n  (\n    avg(windows_os_physical_memory_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"})\n    /\n    avg(windows_cs_physical_memory_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"})\n    * 100\n  )"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{instance=\"$instance\",job=\"integrations/windows_exporter\"}[$__rate_interval])",
     "legendFormat": "\"{% raw %}{{volume}}{% endraw %}\" read"
    },
    {
     "expr": "- rate(windows_logical_disk_write_bytes_total{instance=\"$instance\",job=\"integrations/windows_exporter\"}[$__rate_interval])",
     "legendFormat": "\"{% raw %}{{volume}}{% endraw %}\" written"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_split_ios_total{instance=\"$instance\",job=\"integrations/windows_exporter\"}[$__rate_interval])",
     "legendFormat": "\"{% raw %}{{volume}}{% endraw %}\" io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage \"C:\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  max by (volume) (\n    windows_logical_disk_size_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\",volume=\"C:\"}\n    -\n    windows_logical_disk_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\",volume=\"C:\"}\n  )\n)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (volume) (\n    windows_logical_disk_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\",volume=\"C:\"}\n  )\n)",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\n  windows_logical_disk_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}\n  /\n  windows_logical_disk_size_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}",
     "legendFormat": "{% raw %}{{volume}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk Fill Up Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  windows_logical_disk_size_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}\n  -\n  windows_logical_disk_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}\n)\n/\nderiv(\n  windows_logical_disk_free_bytes{instance=\"$instance\",job=\"integrations/windows_exporter\"}[3d]\n)\n> 0",
     "legendFormat": "{% raw %}{{volume}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{instance=\"$instance\",job=\"integrations/windows_exporter\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "- rate(windows_net_bytes_sent_total{instance=\"$instance\",job=\"integrations/windows_exporter\"}[$__rate_interval])",
     "legendFormat": "Transmitted"
    }
   ]
  }
 ]
}