---
- name: define start delay for 1password services
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: count number of services
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: "^.*-1password = {"
        state: absent
      with_fileglob: ../configs/*.nix
      check_mode: true
      register: output
      changed_when: false

    - name: define start max delay in seconds
      ansible.builtin.set_fact:
        one_password_max_delay: "{{ output | community.general.json_query('results[?found==`1`]') | length * 3 }}"

    - name: set start max delay in seconds
      ansible.builtin.replace:
        path: ../configs/variables.nix
        regexp: 'one_password_max_delay = ".*";'
        replace: 'one_password_max_delay = "{{ one_password_max_delay }}";'
