---
- name: download config
  hosts: server
  become: false
  gather_facts: false
  tasks:
    - name: create a directory
      ansible.builtin.file:
        path: ../configs
        state: directory
      delegate_to: localhost
      become: false

    - name: copy config from server to local machine
      ansible.posix.synchronize:
        mode: pull
        src: /etc/nixos/configuration.nix
        dest: ../configs
        rsync_opts: "--ignore-existing"
