---
- name: include a play to configure in-memory inventory
  ansible.builtin.import_playbook: inventory.yml
  tags:
    - prepare
    - upgrade

- name: include a play to install requirements for ansible
  ansible.builtin.import_playbook: python.yml
  tags:
    - prepare
    - upgrade

- name: include a play to save connection parameters on server
  ansible.builtin.import_playbook: connection-parameters.yml

- name: include a play to configure connection parameters
  ansible.builtin.import_playbook: technical-account.yml
  tags: prepare

- name: include a play to configure disks
  ansible.builtin.import_playbook: disks.yml
  tags: prepare

- name: include a play to upload dashboards to the server
  ansible.builtin.import_playbook: dashboards.yml
  tags: dashboards

- name: include a play to download config
  ansible.builtin.import_playbook: download-config.yml
  tags: prepare

- name: include a play to upgrade nixos
  ansible.builtin.import_playbook: upgrade-nixos.yml
  tags: upgrade

- name: include a play to upgrade services
  ansible.builtin.import_playbook: upgrade-services.yml
  tags:
    - prepare
    - upgrade
